site_name: notebook
repo_url: https://github.com/zjuchenyuan/notebook/
site_description: 我的技术笔记本~
site_author: chenyuan
theme:
  name: 'material'
docs_dir: 'mdfiles'
site_dir: 'docs'
edit_uri: 'edit/master/'
extra_javascript:
    - assets/js/instantclick.min.js
    - assets/js/index.js
copyright: '<a href=http://www.beian.miit.gov.cn/>浙ICP备15043819号-2</a>&nbsp;&nbsp;<a target=_blank href=http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010602007826><img src="/assets/images/beian.png" height=14px>浙公网安备 33010602007826号</p></a>'
pages:
    - Home: README.md
    - Python: 
        - Python: Python.md
        - Gist Python一些常用代码片段: gist.md
        - Course Python程序设计: PythonCourse.md
    - Programming Languages:
        - BASH: BASH.md
        - BAT批处理: BAT.md
        - C语言: C.md
        - Java: 
            - Java: Java.md
            - S2-045: S2-045.md
        - JavaScript: JavaScript.md
        - PHP: PHP.md
        
    - Web:
        - CDN: CDN.md
        - cURL: cURL.md
        - Favorites: 
            - Favorites: Favorites.md
            - Github Project Recommendation: GithubProjectRecommendation.md
            - 更多链接: Links.md
        - Flask: Flask.md
        - MySQL: MySQL.md
        - Nginx: Nginx.md
        - RabbitMQ: RabbitMQ.md

    - Development:
        - Developer: Developer.md
        - Docker: Docker.md
        - ETH: ETH.md
        - Git: Git.md
        - Jekyll: Jekyll.md
        - Paper Reading: PaperReading.md
        - WindowsSoftware: WindowsSoftware.md

    - Fuzzing:
        - DFSan: dfsan.md

    - Linux:
            - Linux-backup: Linux-backup.md
            - Linux-setup: Linux-setup.md
            - Linux-SSH: Linux-SSH.md
            - Linux-cli: Linux-cli.md
            - Linux-VirtualBox: Linux-VirtualBox.md
            - Ubuntu: Ubuntu.md

    - My Projects:
        - ZJU grs helper: zjugrshelper.md
    
    
extra:
  social:
    - type: 'github-alt'
      link: 'https://github.com/zjuchenyuan'
    - type: 'envelope'
      link: 'mailto: py3io.chenyuan@qiushi.ac.cn'
 
markdown_extensions:
  - admonition
  - urlize
  - codehilite
  - smarty
  - sane_lists
  - meta
  - toc:
      permalink: True